### ISSUE TITLE
Willing to contribute

### ISSUE THREAD

**Issue by bansaltushar014** [shrujalshah28/node-typescript-express-mongo#93]
Hi, 

I am a beginner and willing to contribute to this project. Could you please tell how can I start?

**Comment by shrujalshah28** [comment]
Hi @bansaltushar014 

Thank you for consideration. Please look at [Readme.md](https://github.com/shrujalshah28/node-typescript-express-mongo/blob/master/README.md) to get started and you can always look at code for better understanding. And feel free to create a pull request for any improvements you think.

**Comment by bansaltushar014** [comment]
Sure, I  have started looking into this project. If I come up with something where I can contribute then I would create an issue. Thanks.
